const fs = require('fs');
const path = require('path');
const cp866 = require('../cp866');

/**
 * Генерирует C++ header файл
 *
 * @param {string} outPath   - путь к .h файлу
 * @param {number[][]} data  - массив [256][8]
 * @param {number} width     - ширина символа (4..8)
 */
function writeHeader(outPath, data, width) {
    if (!Array.isArray(data) || data.length !== 256) {
        throw new Error('Data must be array [256][8]');
    }

    const guard = makeIncludeGuard(outPath);
    const name = path.basename(outPath, '.h');

    let out = '';

    // Заголовок
    out += `#ifndef ${guard}\n`;
    out += `#define ${guard}\n\n`;
    out += `#include <stdint.h>\n\n`;

    out += `// Generated by font2header\n`;
    out += `// Char size: ${width}x8\n\n`;

    out += `static const uint8_t ${name}[256][8] = {\n`;

    // Символы
    for (let i = 0; i < 256; i++) {
        const bytes = data[i];

        if (!Array.isArray(bytes) || bytes.length !== 8) {
            throw new Error(`Invalid glyph data at index ${i}`);
        }

        const hex = bytes.map((b) => `0x${b.toString(16).padStart(2, '0')}`).join(', ');

        const comment = makeComment(i);

        out += `  {${hex}}, ${comment}\n`;
    }

    out += `};\n\n`;
    out += `#endif // ${guard}\n`;

    fs.writeFileSync(outPath, out, 'utf8');
    console.log('Header written to', outPath);
}

/**
 * Формирует include guard
 */
function makeIncludeGuard(filePath) {
    return (
        path
            .basename(filePath)
            .toUpperCase()
            .replace(/[^A-Z0-9]/g, '_') + '_'
    );
}

/**
 * Комментарий вида:
 * // Char 032 ( )
 * // Char 065 (A)
 * // Char 0x80 (А)
 */
function makeComment(code) {
    let label;
    if (code >= 0x20 && code <= 0x7e) {
        label = String.fromCharCode(code);
    } else {
        const u = cp866[code];
        if (u && u >= 0x20) {
            label = String.fromCharCode(u);
        } else {
            label = '';
        }
    }

    const num =
        code < 32 || code >= 127
            ? `0x${code.toString(16).padStart(2, '0').toUpperCase()}`
            : code.toString().padStart(3, '0');

    return `// Char ${num} (${label})`;
}

module.exports = {
    writeHeader,
};
